# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x61\x64\x64ressbook.proto\x12\x08tutorial\"\x94\x01\n\x02t1\x12\r\n\x01\x61\x18\x01 \x01(\x05:\x02\x31\x30\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x12\x0c\n\x02id\x18\x04 \x01(\x05H\x00\x12\x1e\n\x01m\x18\x05 \x03(\x0b\x32\x13.tutorial.t1.MEntry\x1a(\n\x06MEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\none1_oneof')
)




_T1_MENTRY = _descriptor.Descriptor(
  name='MEntry',
  full_name='tutorial.t1.MEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tutorial.t1.MEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.t1.MEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=166,
)

_T1 = _descriptor.Descriptor(
  name='t1',
  full_name='tutorial.t1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='tutorial.t1.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='tutorial.t1.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.t1.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.t1.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m', full_name='tutorial.t1.m', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_T1_MENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='one1_oneof', full_name='tutorial.t1.one1_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=180,
)

_T1_MENTRY.containing_type = _T1
_T1.fields_by_name['m'].message_type = _T1_MENTRY
_T1.oneofs_by_name['one1_oneof'].fields.append(
  _T1.fields_by_name['name'])
_T1.fields_by_name['name'].containing_oneof = _T1.oneofs_by_name['one1_oneof']
_T1.oneofs_by_name['one1_oneof'].fields.append(
  _T1.fields_by_name['id'])
_T1.fields_by_name['id'].containing_oneof = _T1.oneofs_by_name['one1_oneof']
DESCRIPTOR.message_types_by_name['t1'] = _T1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

t1 = _reflection.GeneratedProtocolMessageType('t1', (_message.Message,), dict(

  MEntry = _reflection.GeneratedProtocolMessageType('MEntry', (_message.Message,), dict(
    DESCRIPTOR = _T1_MENTRY,
    __module__ = 'addressbook_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.t1.MEntry)
    ))
  ,
  DESCRIPTOR = _T1,
  __module__ = 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.t1)
  ))
_sym_db.RegisterMessage(t1)
_sym_db.RegisterMessage(t1.MEntry)


_T1_MENTRY._options = None
# @@protoc_insertion_point(module_scope)
